apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-pe-code-review
  description: AI PE code review project
spec:
  type: library
  lifecycle: experimental
  owner: user:m-sruthika-10
