name: Sync guardrails.txt from source repo

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC (5:30 AM IST)
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-guardrails-from-repo.yml'

jobs:
  sync-guardrails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Configure Git credentials
        run: |
          git config --global credential.helper "store --file=.git-credentials"
          echo "https://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@github.com" > .git-credentials
          chmod 600 .git-credentials
          git config --global --add safe.directory /github/workspace

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          ref: main
          # repository: m-sruthika-10/AI-PE-code-review
          # token: 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 # Your working PAT

      - name: Fetch guardrails.txt from source repository
        env:
          SOURCE_REPO: 'm-sruthika-10/main' # Source repository where guardrails.txt resides
          SOURCE_BRANCH: 'dev_test' # Source branch
          REPO_ACCESS_TOKEN: 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 # Your working PAT
        run: |
          set -x # Enable verbose logging
          curl -H "Accept: application/vnd.github.v3.raw" \
            -H "Authorization: Bearer $REPO_ACCESS_TOKEN" \
            "https://api.github.com/repos/$SOURCE_REPO/contents/guardrails.txt?ref=$SOURCE_BRANCH" \
            -o guardrails.txt || { echo "Error fetching guardrails.txt; check token, repository, or file existence."; exit 1; }
          # Verify file was downloaded
          if [ ! -f guardrails.txt ]; then
            echo "Failed to fetch guardrails.txt; exiting."
            exit 1
          fi

      - name: Commit guardrails.txt and create PR
        env:
          REPO_ACCESS_TOKEN: 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 # Your working PAT
          GITHUB_TOKEN: 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 # Your working PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "action@github.com"
          git checkout -b sync-guardrails-$(date +%s)
          git add guardrails.txt
          if git diff --staged --quiet; then
            echo "No changes to guardrails.txt; skipping commit."
          else
            git commit -m "Sync guardrails.txt from $SOURCE_REPO dev_test branch"
            git push origin sync-guardrails-$(date +%s)
            gh pr create --title "Sync guardrails.txt from $SOURCE_REPO" --body "Automated sync of guardrails.txt" --base main --head sync-guardrails-$(date +%s)
          fi
