name: Sync Confluence Java Coding Standards to GitHub
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  sync-confluence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for PR creation to compare branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests html2text

      - name: Fetch Confluence Page
        env:
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_BASE_URL: ${{ secrets.CONFLUENCE_BASE_URL }}
          CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
        run: |
          python -c "
          import requests
          import html2text
          import os
          url = f'$CONFLUENCE_BASE_URL/rest/api/content/$CONFLUENCE_PAGE_ID?expand=body.storage'
          auth = ('$CONFLUENCE_USERNAME', '$CONFLUENCE_API_TOKEN')
          response = requests.get(url, auth=auth)
          response.raise_for_status()
          data = response.json()
          content = data['body']['storage']['value']
          # Convert XHTML to Markdown
          h = html2text.HTML2Text()
          h.ignore_links = False
          markdown = h.handle(content)
          # Save to file
          os.makedirs('docs', exist_ok=True)
          with open('docs/java_coding_standards.md', 'w') as f:
              f.write('# Java Coding Standards\n\n' + markdown)
          "

      - name: Commit and Push to New Branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b confluence-sync-$(date +%s)
          git add docs/java_coding_standards.md
          git commit -m 'Update Java Coding Standards from Confluence' || echo "No changes to commit"
          git push origin confluence-sync-$(date +%s)
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          title: 'Update Java Coding Standards from Confluence'
          body: 'Automated update of Java Coding Standards from Confluence page.'
          branch: confluence-sync-$(date +%s)
          base: main
          delete-branch: true # Delete branch after PR is merged

      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
